version: '3'
services:
  frontend:
    build:
      context: frontend
    image: vin3gum/myfrontend:1.0
    depends_on:
      - backend
    ports:
      - "9000:80"
    volumes:
      - frontend-var-log:/var/log
    environment:
      BACKENDLB: test
  frontendlog:
    build:
      context: awslogs
    image: vin3gum/frontendlogs:1.0
    depends_on:
      - frontend
    volumes:
      - frontend-var-log:/mnt/log:ro
  backend:
    build:
      context: backend
    image: vin3gum/mybackend:1.0
    volumes:
      - backend-var-log:/var/log
  backendlog:
    build:
      context: awslogs
    image: vin3gum/backendlogs:1.0
    depends_on:
      - backend
    volumes:
      - backend-var-log:/mnt/log:ro
volumes:
  frontend-var-log:
  backend-var-log:
